CREATE TABLE IF NOT EXISTS `User` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `email` TEXT
);

CREATE TABLE IF NOT EXISTS `Weight` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `user_id` INTEGER NOT NULL, `weight` REAL NOT NULL,
  `timestamp` INTEGER NOT NULL, FOREIGN KEY(`user_id`) REFERENCES
  `User`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS `FastTimer` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   `user_id` INTEGER NOT NULL, `start` INTEGER NOT NULL,
    `stop` INTEGER NOT NULL, `note` TEXT, `completed` INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS `GymTimer` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `work` INTEGER NOT NULL, `rest` INTEGER NOT NULL,
  `round` INTEGER NOT NULL, `name` TEXT NOT NULL COLLATE NOCASE
  );